[project]
name = "lab_calc"
version = "0.1.0"
description = "lab1"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.2",
]
[tool.mypy]
python_version = "3.8"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true
